---
healthchecks_wrapper_ping_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34323163316532306365303665343937643533373263313831316236373639306266636537303338
  3361383831636662393839336532376565336137613136610a626263383266346665336538386261
  61643232636337623262326235316164653166616137313861353365643965613265616261316637
  3166326438646262300a373066383535376537333830663035363662613931396133373233653764
  66356239646334346165656333326633343638343038333535353433353633373038
