---
ntfy_stack_name: ntfy
ntfy_config_folder: '{{ docker_config_dir }}/{{ ntfy_stack_name }}'
ntfy_docker_volumes:
  cache: '{{ docker_volumes_dir }}/{{ ntfy_stack_name }}/cache'
  users: '{{ docker_volumes_dir }}/{{ ntfy_stack_name }}/users'

ntfy_auth:
  users:
    - username: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        35393666383935616663346638396637303966396563356461333561623231393834386539646265
        3432633630326337306536633234306438643963373830650a366633306333393830316136373733
        30613234626266363464306366656534666339326237363034353334653331643634643563663730
        6238356335613537370a366533386163653633376134666561336461666661646634316635333638
        3864
      password_hash: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        34376430663964636338646262633134373634633266303064353230393637323861316538336233
        6437386664346662326237353339376539376465643462650a633836333039393764626235323032
        35616334313361323661363838626532646335373762313131363434343236633064323365373036
        3131633565646338620a633339653232323361643135373162356539316339396431643966396130
        61666432626666636363333133643636666131643533373433313032333832616532383130343766
        65323866656366363438373636663332613638373164313035666262353066313335616136623739
        343330376234386662663837653266386635
      role: admin
    - username: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        32623466363465323665613938396333366361363939653834353862613866666531346262643737
        6635643762666539386163316266376237383030366636630a346439393763393761656162653461
        65313365393037626266306536633038663130363266373163306337626138316534323061353065
        6666366561616662380a383236663561303939636536643564383136393061306135306463373032
        6231
      password_hash: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        30653364306234376530356262633237353765656230663565336137393862396338383563633132
        6364323166363031316337343030663262643737643961310a316534303265343836623436383261
        31366238666463353830343539333065336663316162643566303261376666653331373835376336
        3538363436316637330a363931343163356664646134633430356363376462613339356361653635
        33633936313737666461333363363036656536623839326664373366376234323437636231613430
        35636266383236383531656339383365383634623837353866663334643731633432613933363535
        623562326435653136653637303831633664
      role: user
      access:
        - topic: alerts
          permission: wo
      tokens:
        - token: '{{ ntfy_tokens.apprise }}'
          label: apprise
        - token: '{{ ntfy_tokens.grafana }}'
          label: grafana
        - token: '{{ ntfy_tokens.healthchecks }}'
          label: healthchecks
