---
docker_compose_dir: '/opt/docker/compose-files'
docker_config_dir: '/opt/docker/config'
docker_volumes_dir: '/opt/docker/volumes'

cron_script_dir: '/opt/scripts'
hc_wrapper_script: '{{ cron_script_dir }}/hc_wrapper.sh'

admin_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65373332356235343234393537373037653862313431656562626436336632643638613231303164
  3061333336633864303439346161656539343061623762640a316331333036396463633839366464
  65616134626363363734373232316638393463366431363934333862623765376430653934663034
  6237313965663363390a373661303032386663336537336330633831626436393961663030656335
  3331

users:
  app_user:
    name: appuser
    group: appgroup

homelab_domain_name: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63656561653262643863623761323262643139393039323734363066376537313534353163653438
  6465386531356230613738393666616561356236646339320a303262313661343231643163303138
  31636632363932373663383038333863666462393833393337376636353532663237363532613134
  6465633438313965380a383933643563643338623165343639636363343736353965346262376562
  6233

monitoring:
  network_name: "monitoring_network"
  prometheus: "prometheus"
  loki: "loki"
  freebox_exporter: "freebox-exporter"
  omada_exporter: "omada-exporter"
  adguard_home_exporter: "adguard-home-exporter"
  redis_exporter: "redis-exporter"

homeassistant:
  ip: "192.168.1.114"
  port: 8123
  exporter:
    port: 9100

omada_controller:
  users:
    exporter:
      name: 'exporter'
      password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        62356166643230636533643130613162383032396133386463386665656633366538376339316563
        3130373839363632366561363362353237613261383634640a663562316634366432353430353734
        35633661323739666339313965623138396334623338313466666534633761356237633666323462
        3030383335363530640a346365363033616161323638326537366566346537333663613063396237
        35366534343231323336306139333431303439323637363466643939316562646132663164636434
        3338646234653230306363663538303063313761626431323761

ovh:
  endpoint: "ovh-eu"
  application_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65393639643235616135326239303432353434333166636436356563353030343334633162306231
    3333366361663635653537636637303330613934633231330a383962646663333864313738373832
    30303135663734613236313461303161646563323934633536363832303961363365636564383738
    3563643563626264380a666334343537636663303933396433343933376434303166663163386464
    38666333323439643237623262353333303034383436346637636266326664323262
  application_secret: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    66656437313665326435613861323262383333316135313836656666646433353736393634323135
    6633666430353766313066353730303337303234363039370a373130333131306130653663386535
    33356263396266653535343663383333323161393032306439633039363531663736626632383538
    3435363164646664340a306565313931666332376131306463373261643733383536303035623036
    61663764383264366332383739333533616335376536393236386461383536656132396566376637
    3338373833626138616664633237373666366162363335343365
  consumer_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    31636237323233653335656462313133376237633562636366313531303539346239646464666534
    3561633831393130343231316439323739663161373964310a653162343434623535313438383662
    37333561383739366461346262386139326361396633626437643265356236303863396638623332
    3235396166346537360a613731366464326263616336633038633832306531613864633966653938
    32663738643435633332613965623335353566373661643864633032363937656461303965653034
    6630376530616165376634633435383135643462646333616238
  email: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    38393837373336663839616365376133346666633661366637396662373933323933313162306635
    3533333933316338663865373834633433336163633730630a656438653665343739303562333266
    33653663303836323338343364336230373162376366353434626534653631646661346261643139
    3138393233376431320a623537663465333331376133326236323466386530393535333530366161
    63336465666663366639356363613337346164386465356663656439666662626461

traefik:
  network_name: "traefik_network"
  log_folder: '{{ docker_volumes_dir }}/traefik/logs'

adguard_home:
  users:
    admin:
      name: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        34356136613636613762303833663539363964613962366364346162623133333764393439306232
        3431393363333634363065646335393434366331366434330a376436646139633938393231633638
        38626331663639313133313662366435653765306338623861343237343632343638316466363830
        6431393839363034380a616436343330363236616165303831336236656163643235663233636661
        6132
      password_hash: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        30326162326362376163323266643561626630653865336132633830316332653132323930646361
        3330303634366436366563626166313137396236366330660a326561383564356261656436363463
        34623239613833643231653464346363386266316532303961323065346338663639616135653963
        6266306334633437620a363262366237373831633933343035613262316531663031346232353239
        62343131313761396361326139343337633932643233356465373761613532663337343934623065
        38653036356162633562343832646533333434323136316632393439616165333262386536366161
        376166363131336466346132353761663063
    exporter:
      name: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        33656331343930623738383830646432306261313232383930326531383066363162336631366434
        3161656535623531633130343439323564363333326161390a666562303665623332653765393634
        62396163353034636362333434633433646534663839353234663962353537373961336265616633
        3162313230623637360a323464626135616133616161396539336437636538366133613865623739
        3562
      password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        37383734313733336564323335383239303264346464636266343862366634353130383339643263
        3634303738366163333134353931623862663539633537360a396239313535653336666333303334
        61383739623766623031316564386134306566303336623236393765643436313364663531613732
        3535343239616462630a653966326236303234616265343531303866393634386234313432666465
        33383931663737366530303233373465323563613362366137383866306564613834333364313133
        6533636530633534336565333236343437663664646238326264
      password_hash: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        30653631326537333661343063353333623066356161366462393439303533376366343662323663
        3563626239623639643130353666643263633665616561630a616265363263396564306664626365
        65636234633130366238356631326532366234613630646664313065346532323661383666383733
        6234333565376332350a333636386263326564353162373365393566313630396365616134363861
        39316331633337653763303138383737306565393366653063313863363838336632363336366533
        61623636356536316139613731353165323966353662643864336664393961383766303136303665
        343433346131336561316262666535316530

pronote2calendar:
  child_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39373732616466656333633337643535623633613534356639626132383061663739373435623136
          3666333438343864343065613865616231376135663536350a316634613530386333313535393463
          62353531623335366335636234303937376565343261396263366166393539323563616135373861
          3035316366393730340a373830313965353632386661303030373238326432306535376537623230
          3536
  calendar_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35633333656636306436643534323661306238643032326238353439326564386337653132363439
          6261336337343761363664313136663232653732363439650a383534356133396638363565393936
          34353735356565633236373139643365346133646537626637326434396263376334336532333830
          6437333862373362660a346139393764306239373333386663666366313063613330343133343630
          31323936336439663738633536383765613932373965646463383361353463646361

authelia:
  redis:
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33323632643731636364356431313336303032613434376331343538313636396436666464626662
      3264303664303765303633373336373234663561366265390a316665393961366639393531656163
      38343438336132343461663964636230326631633631356536636430373433643437663231613765
      6535646564333262340a336665323631653765663535396138386634346437393237323236343332
      33616666333839343863323762343361613736393164623632356363386661353531643930353832
      35666234383030663563376138366534663432323032313561366139363831363636393765376664
      66653836663532343638306637613437626361333432313931303962313862623136666338323662
      38313033373361323663

paperless_ngx:
  redis:
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30376465386633336662313466313637306263306131323830303430636234336166313137383265
      6233613039663032383739626437383436613936626630390a616130316634346238383236346532
      33623266396231333761636366653037303466343131393037343162383635323232386264316437
      6164633063303535630a363962616163663663636165326533363730346433653930366465623832
      65393731343866646162616162386135616564613738346366643563643761303134386134626365
      61656265653338616338343630653035333032366464653561313766323532316634343263386263
      38653439333236336636343738396531643439323539346364633139656466653839333865373737
      38643031343661306235

crowdsec:
  bouncer_api_keys:
    traefik: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37643163363831303737323735643637343034633737646632373634623432653731353632643064
      3737613766343034383432323861303764366439636636330a333265373432396166356132393566
      31383335613633626561343261626430653362613830353263373364393034303964633630383631
      3434316332643363300a383032616431663836666339333863373134626330656463343538383030
      34613066383538356163383163613064646435303632333735343938323762363865386630396463
      3133623764386666636131633232343065663234336661636636
