---
auth_oidc_clients:
  grafana:
    client_id: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65383433373863353331623338333535343433666538643932323437373964313566323734366336
      3733363263643164343862373166343738393934306634320a643437666638373561366435653333
      37333138386631636333316361323930313235663333313033666462666535646463356163653738
      6265356364333331310a313531303735643730373137653562323763323333306261336365326531
      35636461376332376364663336323063643765336362396632376137383630366639663038633138
      38356332643366366137326130383131323161366130656634393865613132333336356339343732
      65623761623164353664306234636561373766356239643766313638353066333662633162396439
      35313334306233626331
    client_secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61616662363930333937643937303135663234666237656261336166613162663138666564313162
      6334373338333666366466363735623435653431623638610a386339366264306162333231386130
      61346633333933363736366165353736316133656330373430666265353661613931333262633935
      3061363832396538330a643666613435303833366136623164383362353532393536356661303464
      63363566633439346230363336366466326535626333653938633838626535626137613063373737
      61373338346139383832313237306537346535386339333330303834666533306131353966626564
      35363361663933346633306666346562623432393730313538353337643037623734393436643365
      39323735363232323565
    client_digest: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      62323863306336646464313663333931643531316465656336663366373739383733643131633766
      3133616166376539396535353936303535393465616332340a393338633966316336653035343463
      61346463343835393033636232653365363438663739383439376461376234393863626535306138
      6638383534663533300a626264306637656164316632303731343334353135333430313365613336
      61303862393438303436613032643766356262663534653166323766373963336661653038336231
      64393433306138666565396637316238656636643436396437666566386235626233333036303134
      32396261396562356534376566613637353862323238383765336666366330323366353832636337
      38623435346235353936323661353137316262653136663835313132353131353064353337633432
      62633165633561363837613337616162376633313464613564393834316331333534373861383239
      66346663373932323961653432303861396334643162623832353033386334386336663331376537
      386161326335616463303366626138353533
