---
auth_oidc_clients:
  grafana:
    client_id: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65383433373863353331623338333535343433666538643932323437373964313566323734366336
      3733363263643164343862373166343738393934306634320a643437666638373561366435653333
      37333138386631636333316361323930313235663333313033666462666535646463356163653738
      6265356364333331310a313531303735643730373137653562323763323333306261336365326531
      35636461376332376364663336323063643765336362396632376137383630366639663038633138
      38356332643366366137326130383131323161366130656634393865613132333336356339343732
      65623761623164353664306234636561373766356239643766313638353066333662633162396439
      35313334306233626331
    client_secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61616662363930333937643937303135663234666237656261336166613162663138666564313162
      6334373338333666366466363735623435653431623638610a386339366264306162333231386130
      61346633333933363736366165353736316133656330373430666265353661613931333262633935
      3061363832396538330a643666613435303833366136623164383362353532393536356661303464
      63363566633439346230363336366466326535626333653938633838626535626137613063373737
      61373338346139383832313237306537346535386339333330303834666533306131353966626564
      35363361663933346633306666346562623432393730313538353337643037623734393436643365
      39323735363232323565
    client_digest: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      62323863306336646464313663333931643531316465656336663366373739383733643131633766
      3133616166376539396535353936303535393465616332340a393338633966316336653035343463
      61346463343835393033636232653365363438663739383439376461376234393863626535306138
      6638383534663533300a626264306637656164316632303731343334353135333430313365613336
      61303862393438303436613032643766356262663534653166323766373963336661653038336231
      64393433306138666565396637316238656636643436396437666566386235626233333036303134
      32396261396562356534376566613637353862323238383765336666366330323366353832636337
      38623435346235353936323661353137316262653136663835313132353131353064353337633432
      62633165633561363837613337616162376633313464613564393834316331333534373861383239
      66346663373932323961653432303861396334643162623832353033386334386336663331376537
      386161326335616463303366626138353533
  paperless_ngx:
    client_id: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38363131636666326161396662353866343561666662396463333466303034316663306464313834
      3337636663393461346665386461373465613931386566300a303635373962643835326165313237
      64663266623366343462373461356261613463393731343139313537303836393232653766306332
      3138646164636335630a623861356536653265626133623437383239613066653263323134626662
      33353266633832303063313732613639636630663837616365626634656637356166346636343064
      61343565613337616230393939323034376536353163663630633234326335393366623339616365
      61313836383131666231613765323065666562346430313430343637366661343263396265643035
      63386462643535316431
    client_secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34316631326362656532303534316365306532353266386165616330653263393931353533363964
      3265303431666562303636653839303866323066393531380a356531343461306536303333306661
      37323938393562306466303065363034633330623131656562376165386630336133343264383935
      6662303338623438610a336164333234363332346662383162333763346164373563346464363363
      65353435343034633663613365373933623961653136326564323039323565323037303331633961
      38363733343332323837333861356433303964633833323432656437303730303964316332636666
      30363736336463306565386230306132353865653934383761383538666661623038646238393162
      61663666613262373431
    client_digest: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      63383534323831376438613733366235383366616435303365653562663539616633363932396634
      3764353733613564613463336237383034343834386661640a353631396165616138326566326664
      38306462623764303466316634343034326534383035326232376430366561383533393362653461
      6262643531396466370a383731636538646333636166316566306464373330616532336363613437
      38323462376334653762363431663638613233363665303336393636363766393435353131343531
      62343430643365386639623132373131383732323566376364663837626236666336643238343636
      32393864653761363530633831616630386139353964366637613338316336626465653631663063
      65333032303430653162333538343934616235316362373161366361613038616262343930643036
      30323434326262343435323536346662333264313232306430653333653532303535383464386538
      61303734373431373462643539343061663134346230373731333366633730613332613065613535
      376439373932383561633833633363313761
