---
ntfy_tokens:
  apprise: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    36356666646464626431306665653066376666623835373932386666656364303932623065623364
    3066343930346637623638616664633834383231333630660a643630353332343030303139303339
    61326136653063623637636234376666633437353437663462326538643535613466646536343264
    3264376164303764370a643933653932616334326337323265326661363736393839393163336263
    33326365303132623030623564316163393464333365613765393736656164626462383434666561
    6530643764386636666661393339343333643235376136633264
  grafana: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    30383338373133666434306564663766383432636531646464313336656135386231323436343936
    6434363064643362393862303463656431326165666430320a336166623137353064326430613938
    63643935626336333834633562386532333830613163636531663438666337346463353262633637
    3333376361643231640a653266316136333534666430613431643835643736303065323634313034
    30656666643762613730333563613165396633313035663563363062656630373438386635616135
    6234643336616632633437653931623537623334303964663165
