---
paperless_ngx_stack_name: paperless_ngx
paperless_ngx_config_folder: '{{ docker_config_dir }}/{{ paperless_ngx_stack_name }}'
paperless_ngx_docker_volumes:
  data: '{{ docker_volumes_dir }}/{{ paperless_ngx_stack_name }}/data'
  redisdata: '{{ docker_volumes_dir }}/{{ paperless_ngx_stack_name }}/redisdata'

paperless_ngx_smb_share:
  username: paperlessngx
  password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32663161346231306164326133396333396439396161303932386539623134303233383833386566
    6163646435373863353035656433663636313539306237330a656337373736643766663361366632
    37343161313037333162653335383434393739646365623835643166653133386564613134386235
    3338396461363134320a396134643337353365626564653336363531366338666662613666386665
    34353637316364623634346639633535386663316431663831366564663764633161643261613235
    6666326530613162373834366637323266383866336637663434
  domain: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    30613638623435373739373931396634623834333936313330383730363663663365303339323462
    3831363861353364306165393435636636306538306464630a613266633039623263383935343432
    33393466313963376231353932306264623738613565653336346562616432666565313564353537
    3531633065666430340a616562376639333166623339623361616262633763623537333137393033
    3534
  path: //192.168.1.76/Paperless

paperless_ngx_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35333333616164363330663537376237326535343237376630313063643832386563363739363638
  3363326539653135636231653235626139623263303061340a653833323139373739336562633966
  35333563313835656261393232333538396238326561356261663135653632376338666135646164
  3736393133306233310a356637393932336365316635363330346233336665616266313730663163
  62623534346636326162656330363738346366363037303765373936623737373937636337613530
  34323231376563396462303734336137373637313433326264316664343931646436336137623536
  37333338383939336461336666313130653861333439303834353336356632326336346535376566
  32633231393539343435
