---
paperless_ngx_stack_name: paperless_ngx
paperless_ngx_config_folder: '{{ docker_config_dir }}/{{ paperless_ngx_stack_name }}'
paperless_ngx_docker_volumes:
  data: '{{ docker_volumes_dir }}/{{ paperless_ngx_stack_name }}/data'
  media: '{{ docker_volumes_dir }}/{{ paperless_ngx_stack_name }}/media'
  export: '{{ docker_volumes_dir }}/{{ paperless_ngx_stack_name }}/export'
  consume: '{{ docker_volumes_dir }}/{{ paperless_ngx_stack_name }}/consume'
  redisdata: '{{ docker_volumes_dir }}/{{ paperless_ngx_stack_name }}/redisdata'

paperless_ngx_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35333333616164363330663537376237326535343237376630313063643832386563363739363638
  3363326539653135636231653235626139623263303061340a653833323139373739336562633966
  35333563313835656261393232333538396238326561356261663135653632376338666135646164
  3736393133306233310a356637393932336365316635363330346233336665616266313730663163
  62623534346636326162656330363738346366363037303765373936623737373937636337613530
  34323231376563396462303734336137373637313433326264316664343931646436336137623536
  37333338383939336461336666313130653861333439303834353336356632326336346535376566
  32633231393539343435
