---
apprise_stack_name: apprise
apprise_config_folder: '{{ docker_config_dir }}/{{ apprise_stack_name }}'
apprise_docker_volumes:
  storage: '{{ docker_volumes_dir }}/{{ apprise_stack_name }}/storage'
  attach: '{{ docker_volumes_dir }}/{{ apprise_stack_name }}/attach'
  plugin: '{{ docker_volumes_dir }}/{{ apprise_stack_name }}/plugin'

apprise_smtp2go:
  apikey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    36623264373737613865653863313764383834346463336434643931633232333635643363343332
    6365373265336464666437616363333130633735633264650a393131323335626330323734613639
    35303164303364363538633839613737316262386436383236376535326131383334373064353537
    6634633731633135360a653936316239643635626132633965313061653062393338616462373530
    38383365373030333836353038303266376433346136656437383830376634663964306336373633
    3038353363653063336566636139353765643336363463303738
  username: 'no-reply+apprise'
  domain: '{{ homelab_domain_name }}'
  sender: 'Homelab notifications'
  to: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    62656433356535323035363066336438333132363630643838633961656530633330363765333762
    3661383662626632353763396266363232383437373333640a393965646436626333326139356131
    38616334346365623564663832333366663561636266306162653866636435626566343333396233
    3935303135616434610a393033373866333966386238623937383965636466373335333034396533
    32636261313065383865306561393230623638343935376435613134666366353365

apprise_ntfy:
  host: 'ntfy'
  token: '{{ ntfy_tokens.apprise }}'

apprise_freemobile:
  user: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    61326337623332383431376366663338336166336635626337623064656466313539386161653539
    3230383632646466396561393666396363303865663030660a663235303337383836366535633734
    38386638386265326639633830333564613961373531616437376362363964353137316263336439
    6561346639623538320a366261653035646530643062626366323237623763376165636434663365
    3534
  apikey: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    62383434373532633834383161353065346561393133633632396166353262363936313137313765
    3131396465633861343632656636376461326434653666310a343337343664346237613736613938
    31623130623066373231313264346366346233666466336562323465646334316637613130623864
    3538663232663034390a346363383363376534353334656538633663383932633030613663323166
    3764
