---
authelia_stack_name: 'authelia'
authelia_config_folder: '{{ docker_config_dir }}/{{ authelia_stack_name }}'
authelia_docker_volumes:
  data: '{{ docker_volumes_dir }}/{{ authelia_stack_name }}/data'
  redis: '{{ docker_volumes_dir }}/{{ authelia_stack_name }}/redis'
authelia_session_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64643038333063376534336265356336383266623338303264376633343833623965356139663763
  3832626637316663303138636664363265656463666166390a313363393463396436383162653762
  32373938383332663661353031646135653461323334633638656665333331343332626139623930
  3431356565303762300a366239336661653864616532353139653964396432376162653934313532
  31316265636261653838333636383136333261633033373339303139643136636638376462623836
  66326162356564666364666535326662316532323733363866353238306265653564386662636132
  63363363363630393035396561386232383864376332613138643663643335613531633831663537
  63653238326331663733
authelia_storage_encryption_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34366438353465623566346165353962623162336666383336623066666266316534636339383035
  6163393434326538396133316533393565323434336461380a363534326639636239636430643231
  34626535353736613433376534383538313362346634323636646662313631303965373134366539
  6238663338353333340a373134326538313364393062386334343965666163313434663236656630
  37363864626638666539346638613461626662663235363238653332306332343039366336666264
  63353735326263313338653662343831636665663530386632373865383436346363303465646337
  35353663623139653235616530313631643637653663623632306232643331643939386537643662
  65333230363533613731
authelia_redis_password: '{{ authelia.redis.password }}'
authelia_smtp:
  username: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32333933383664616365323735663337613864303936316138313064646232386236356436643866
    6138383232373762313366383234346337666161646636390a376232353162366563653766373439
    38393933303166363764383862633936376430656235306639643938653635306436383035653337
    3538396330353533370a336265653836633265356462313531353430616634353838613161623937
    3938
  password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65326230666138623165646433303461643436646230363531303031616664313638323766636437
    6161626535313433393163383162393464376634623061650a323231323635383937616336643265
    63623833316139353430333662343236643161366231393736663033656232333337616633646634
    3032373065613831340a366161663438343530356536366337383935396162643333343563613531
    34363762396366353134356562356637623166323438306266396232663036343231656464626438
    6631316335643765663662353163656531633661653039343565
  sender: 'Authelia <no-reply@{{ homelab_domain_name }}>'

authelia_users:
  - username: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33333566306264363036666436373237326337353866383563303164353461636532666565336536
      6433663038363630386231356163653630323333396663310a353737663363366365623561346561
      38653264363834656133373863373066383539316336626461663933643233316365633735363637
      6231633334623730360a336431663630326430333030323134313935356130653936373636363339
      3838
    displayname: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30383935373535306635623961363262623238323633343238646232653536326135373263306633
      6230623039623437313365643130643134333233393662350a666334393033373532393362653462
      66396465393032383136653934386636623538333534336236353437323464396639313564643163
      3431653836653962660a366330613439346463396435393235306239626236643631393939343731
      3031
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37623231386630303066646534656665396438613333616366303466393765393139656166666537
      3165313464656566303837656662613036323532316663380a386632383134383830663633313163
      63653261643166623665356639366166333938643831333539663561393930633464313335616131
      3063613362386665300a313731363539353364333031613663373639383338643364343030383335
      33336665356531356138303536383231343937326632383238326163353866633032613833656638
      33666464363530636461313164306439333565636439656530653738353764616432343363313432
      33333236366630656364383736656631633763643661343738363363633635333764653865643664
      39643234363663336331373739373535613533373738373465356131633961366261613937363262
      36373432366635666636323838313833663437653933346461633338366533353865
    email: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39666138633330353034326136386131633562656265373739326130383038313464363762346263
      3233306566353534383138356662343436663063623466370a646434663634393666656338636638
      65383334343963613132313261333461366266366663306161353731353238396266303830646636
      3638643962666633390a353138663238616630356532333661383737366563343834303333636665
      63393666346665616631643633616366393531343465366435346231363131656432
    groups:
      - admin
