---
authelia_stack_name: 'authelia'
authelia_config_folder: '{{ docker_config_dir }}/{{ authelia_stack_name }}'
authelia_docker_volumes:
  data: '{{ docker_volumes_dir }}/{{ authelia_stack_name }}/data'

authelia_users:
  - username: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33333566306264363036666436373237326337353866383563303164353461636532666565336536
      6433663038363630386231356163653630323333396663310a353737663363366365623561346561
      38653264363834656133373863373066383539316336626461663933643233316365633735363637
      6231633334623730360a336431663630326430333030323134313935356130653936373636363339
      3838
    displayname: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30383935373535306635623961363262623238323633343238646232653536326135373263306633
      6230623039623437313365643130643134333233393662350a666334393033373532393362653462
      66396465393032383136653934386636623538333534336236353437323464396639313564643163
      3431653836653962660a366330613439346463396435393235306239626236643631393939343731
      3031
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37623231386630303066646534656665396438613333616366303466393765393139656166666537
      3165313464656566303837656662613036323532316663380a386632383134383830663633313163
      63653261643166623665356639366166333938643831333539663561393930633464313335616131
      3063613362386665300a313731363539353364333031613663373639383338643364343030383335
      33336665356531356138303536383231343937326632383238326163353866633032613833656638
      33666464363530636461313164306439333565636439656530653738353764616432343363313432
      33333236366630656364383736656631633763643661343738363363633635333764653865643664
      39643234363663336331373739373535613533373738373465356131633961366261613937363262
      36373432366635666636323838313833663437653933346461633338366533353865
    email: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39666138633330353034326136386131633562656265373739326130383038313464363762346263
      3233306566353534383138356662343436663063623466370a646434663634393666656338636638
      65383334343963613132313261333461366266366663306161353731353238396266303830646636
      3638643962666633390a353138663238616630356532333661383737366563343834303333636665
      63393666346665616631643633616366393531343465366435346231363131656432
    groups:
      - admin
