---
- name: Create configuration directory
  ansible.builtin.file:
    path: '{{ ntfy_config_folder }}'
    state: directory
    owner: '{{ users.app_user.name }}'
    group: '{{ users.app_user.group }}'
    mode: '0750'
  become: true

- name: Copy configuration file
  ansible.builtin.template:
    src: 'server.yml.j2'
    dest: '{{ ntfy_config_folder }}/server.yml'
    owner: '{{ users.app_user.name }}'
    group: '{{ users.app_user.group }}'
    mode: '0640'
  become: true
  register: ntfy_configuration_copy_result

- name: Deploy ntfy
  ansible.builtin.include_role:
    name: docker_compose
  vars:
    docker_compose_stack_name: '{{ ntfy_stack_name }}'
    docker_compose_volumes: '{{ ntfy_docker_volumes.values() }}'
    docker_compose_restart: '{{ ntfy_configuration_copy_result.changed }}'
