---
backup_smb_share:
  username: dockerbackup
  password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    64323965376632666530356664656638366537313766613138366666616534353537306661616532
    3963356362656639366636373234393034633964333266640a366564323038623032326530353262
    36386139613561663164363361396135313162363534373133666266386165323262383539666435
    6234323939306364380a373036353131343433353338333461303562633766653136653162396431
    32666464653930633863393831303362373533316436383135336530653339386364
  domain: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    30613638623435373739373931396634623834333936313330383730363663663365303339323462
    3831363861353364306165393435636636306538306464630a613266633039623263383935343432
    33393466313963376231353932306264623738613565653336346562616432666565313564353537
    3531633065666430340a616562376639333166623339623361616262633763623537333137393033
    3534
  path: //192.168.1.76/DockerBackups

backup_folder: /mnt/backup

backup_jobs:
  - name: paperless_ngx
    data_path: "{{ paperless_ngx_docker_volumes.data }}"
    dest: "{{ backup_folder }}/paperless_ngx"
    hour: 2
    minute: 0
    docker_compose_stack_name: "{{ paperless_ngx_stack_name }}"
  - name: healthchecks
    data_path: "{{ healthchecks_docker_volumes.data }}"
    dest: "{{ backup_folder }}/healthchecks"
    hour: 2
    minute: 10
    docker_compose_stack_name: "{{ healthchecks_stack_name }}"
