---
healthchecks_stack_name: 'healthchecks'
healthchecks_config_folder: '{{ docker_config_dir }}/{{ healthchecks_stack_name }}'
healthchecks_docker_volumes:
  data: '{{ docker_volumes_dir }}/{{ healthchecks_stack_name }}/data'

healthchecks_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30333531393961363736666163356166386239633162306663326336353864653365616264623862
  3831373464356138386635626538333038626365623566330a383563663762626132616635363161
  63653630393939623764613538376631396461316463353338333066366564636334666634653765
  3939343537666362650a316364343535333231663732383830333033333739643161353865613963
  37356530613034666661633637633538346461323139643562313332653764333434303461343934
  65326362613534323038336239363862333665636435353363353162353765303135323330653638
  37653566616261316164616266313732653364363230316464646132313931646364613935646533
  63626361353635636265
