---
healthchecks_stack_name: 'healthchecks'
healthchecks_config_folder: '{{ docker_config_dir }}/{{ healthchecks_stack_name }}'
healthchecks_docker_volumes:
  data: '{{ docker_volumes_dir }}/{{ healthchecks_stack_name }}/data'

healthchecks_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30333531393961363736666163356166386239633162306663326336353864653365616264623862
  3831373464356138386635626538333038626365623566330a383563663762626132616635363161
  63653630393939623764613538376631396461316463353338333066366564636334666634653765
  3939343537666362650a316364343535333231663732383830333033333739643161353865613963
  37356530613034666661633637633538346461323139643562313332653764333434303461343934
  65326362613534323038336239363862333665636435353363353162353765303135323330653638
  37653566616261316164616266313732653364363230316464646132313931646364613935646533
  63626361353635636265

healthchecks_smtp:
  host: 'mail-eu.smtp2go.com'
  port: 2525
  username: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    62353333363231623365313933663037616534343138366566386637336139636261316264393039
    6137303533386563313532373331313636386333346565650a653133656463626331623364386338
    30363535376637626133326164363433616430623739366563643834643835343732353038643030
    3861306635636238620a626134656333353065356130393565373031376437613130323036653335
    3061
  password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    61306462323062396637633935346338353535643235643434623639343834366436663632643165
    6338343662623634386639313933613837663563666461610a383136636532303032326532363238
    63313431373262653766313563653731663733623866666666623235306434633833636630376435
    3133643162613664380a633166636465636162333034666461323435623363366265303964613736
    32633562616266656434353733333538663764366635306237383330313862363161613062393338
    6463663333333462643366636363303933343664633262343765
  sender: 'no-reply+healthchecks@{{ homelab_domain_name }}'
